function Xuf:LoadLauncherData()
Xuf:LoadReceiveSync("XUFSync GMXckbucl Razorgore 4 1 Fiwaa Hil Morphium")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Razorgore 4 2 Unplusundeux Bobystill Miewt")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Razorgore 4 3 Freezbee Alisther Yuneling Perefouras")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Razorgore 4 4 Moonarchy Protomix Xdpd")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Vael 2 1 Fiwaa Hil Bobystill Alisther  Protomix Morphium")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Vael 2 2    Miewt  Yuneling Perefouras Aeriis Rhealax")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Boordlord 2 1 Fiwaa Hil Bobystill Alisther  Protomix  Morphium Aeriis")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Boordlord 2 2  Miewt Yuneling Perefouras   Rhealax")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Firemaw 3 1 Fiwaa")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Firemaw 3 2 Hil Alisther  Morphium  Perefouras Aeriis")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Firemaw 3 3 Bobystill Protomix Miewt Yuneling   Rhealax")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Ebonroc 2 1 Fiwaa Hil Bobystill Aeriis  Morphium")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Ebonroc 2 2 Unplusundeux  Protomix Alisther  Rhealax")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Flamegore 2 1 Fiwaa Protomix  Rhealax  Hil Bobystill")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Flamegore 2 2 Unplusundeux Hil  Alisther  Morphium")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Chromaggus 2 1 Fiwaa Yuneling Perefouras Morphium  Miewt")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Chromaggus 2 2 Alisther Protomix  Hil  Bobystill Rhealax Aeriis")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Nefarian 5 1 Fiwaa Hil Bobystill Yuneling  Aeriis")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Nefarian 5 2 Freezbee")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Nefarian 5 3 Unplusundeux Alisther Protomix Miewt  Perefouras")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Nefarian 5 4 Moonarchy")
Xuf:LoadReceiveSync("XUFSync GMXckbucl Nefarian 5 5 Fiwaa  Morphium Rhealax")
end